name: smartpantri
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.6
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.0.1
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^19.0.0
  collection: '^1.17.0'
  http: ^1.2.2
  intl: ^0.19.0
  meta: '^1.1.8'
  webview_flutter: ^4.10.0
  json_annotation: ^4.0.1
  flutter_html: ^3.0.0-beta.2
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+3
  firebase_storage: ^12.3.4
  cached_network_image: ^3.2.1
  dio: ^5.7.0
  path_provider: ^2.0.0
  flutter_dotenv: ^5.0.2
  firebase_admin: ^0.3.0
  image_picker: ^1.0.0
  provider: ^6.0.5
  flutter_colorpicker: ^1.0.3
  image_cropper: ^9.0.0
  device_info_plus: ^11.3.3
  cloud_functions: 5.4.0
  firebase_app_check: 0.3.2+5
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  fl_chart: ^0.71.0
  googleapis_auth: ^1.4.1
  google_fonts: ^6.1.0
  google_api_availability: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  test: any
  mockito: ^5.4.4
  build_runner: ^2.4.9
  fake_cloud_firestore: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - apikeys.env
    - assets/family_shopping_image.png
    - assets/service_account_key.json
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/family_shopping_image.png"