name: smartpantri
description: "A new Flutter project."
publish_to: 'none'  # This prevents accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.6
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.0.1
  firebase_messaging: 15.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/family_shopping_image.png
    - assets/images/carbonara.jpg
    - assets/images/chickenalfredo.jpg
    - assets/images/beefstroganoff.jpg
    - assets/images/vegetablestirfry.jpg


  # Example of how to add fonts (currently commented out)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
