name: smartpantri
description: "A new Flutter project."
publish_to: 'none'  # This prevents accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.6
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.0.1
  firebase_messaging: ^15.1.3
  collection: '^1.17.0'
  http: ^1.2.2
  intl: ^0.19.0
  meta: '^1.1.8'
  webview_flutter: ^4.10.0
  json_annotation: ^4.0.1
  flutter_html: ^3.0.0-beta.2
  google_sign_in: ^6.2.1
  google_sign_in_web: 0.12.4+2
  flutter_facebook_auth: ^7.1.1
  firebase_storage: ^12.3.4
  cached_network_image: ^3.2.1
  dio: ^5.7.0
  path_provider: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
flutter:
  uses-material-design: true


  # Example of how to add fonts (currently commented out)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
